
-- ITEM  table where, all the iems are maintained

  CREATE TABLE "SCOTT"."ITEM" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(50 BYTE), 
	"CATEGORY" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"PRICE" NUMBER NOT NULL ENABLE, 
	"GRADE" VARCHAR2(20 BYTE), 
	"TAG" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"LOCAL_NAME" VARCHAR2(50 BYTE), 
	 CONSTRAINT "ITEM_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

-- USERS table to maintain users data

CREATE TABLE "SCOTT"."USERS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"FIRSTNAME" VARCHAR2(35 BYTE) NOT NULL ENABLE, 
	"LASTNAME" VARCHAR2(35 BYTE), 
	"PHONENUMBER" NUMBER NOT NULL ENABLE, 
	"EMAILID" VARCHAR2(35 BYTE) NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(35 BYTE) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"USER_TYPE" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "USERS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "USERS_UK1" UNIQUE ("PHONENUMBER", "EMAILID", "USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

-- ADDRESS table to maintain address of the user

  CREATE TABLE "SCOTT"."ADDRESS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"USERID" NUMBER NOT NULL ENABLE, 
	"LINE1" VARCHAR2(35 BYTE) NOT NULL ENABLE, 
	"LINE2" VARCHAR2(35 BYTE), 
	"LINE3" VARCHAR2(35 BYTE), 
	"STATE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CITY" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "ADDRESS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "ADDRESS_FK1" FOREIGN KEY ("USERID")
	  REFERENCES "SCOTT"."USERS" ("ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

-- ORDERS table to maintain orders of user

  CREATE TABLE "SCOTT"."ORDERS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"USERID" NUMBER NOT NULL ENABLE, 
	"ORDER_DATE" DATE NOT NULL ENABLE, 
	"ORDER_STATUS" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "ORDERS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "ORDERS_FK1" FOREIGN KEY ("USERID")
	  REFERENCES "SCOTT"."USERS" ("ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

-- ORDERDETAILS table to maintain number of items of order


  CREATE TABLE "SCOTT"."ORDERDETAILS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ORDERID" NUMBER, 
	"ITEMNAME" VARCHAR2(50 BYTE), 
	"ITEMPRICE" NUMBER, 
	"QUANTITY" NUMBER, 
	 CONSTRAINT "ORDERDETAILS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "ORDERDETAILS_FK1" FOREIGN KEY ("ORDERID")
	  REFERENCES "SCOTT"."ORDERS" ("ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

-- COMPLAINTS table to maintain complaints of the user

   CREATE TABLE "SCOTT"."COMPLAINTS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"USERID" NUMBER NOT NULL ENABLE, 
	"TITLE" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(500 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "COMPLAINTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "COMPLAINTS_FK1" FOREIGN KEY ("USERID")
	  REFERENCES "SCOTT"."USERS" ("ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
 
-- TOKENS table for authentication

 CREATE TABLE "SCOTT"."TOKENS" 
   (	"USERID" NUMBER NOT NULL ENABLE, 
	"TOKEN" VARCHAR2(75 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "TOKENS_FK1" FOREIGN KEY ("USERID")
	  REFERENCES "SCOTT"."USERS" ("ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;


-- CODE for maintain state and city list type should state for states and city for cities

  CREATE TABLE "SCOTT"."CODE" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"TYPE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "CODE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;


-- SEQUENCES


-- ITEM SEQUENCE

CREATE SEQUENCE  "SCOTT"."ITEMSEQUENCE"  MINVALUE 1 MAXVALUE 100000 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;

-- USER SEQUENCE

CREATE SEQUENCE  "SCOTT"."USERSSEQUENCE"  MINVALUE 1 MAXVALUE 100000 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;

-- ADDRESS SEQUENCE

CREATE SEQUENCE  "SCOTT"."ADDRESSEQUENCE"  MINVALUE 1 MAXVALUE 100000 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;

-- ORDERS SEQUENCE

CREATE SEQUENCE  "SCOTT"."ORDERSSEQUENCE"  MINVALUE 1 MAXVALUE 100000 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;

-- ORDERDETAILS SEQUENCE

CREATE SEQUENCE  "SCOTT"."ORDERDETAILSSEQUENCE"  MINVALUE 1 MAXVALUE 100000 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;

-- COMPLAINTS SEQUENCE

CREATE SEQUENCE  "SCOTT"."COMPLAINTSSEQUENCE"  MINVALUE 1 MAXVALUE 100000 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;

-- CODE SEQUENCE

CREATE SEQUENCE  "SCOTT"."CODESEQUENCE"  MINVALUE 1 MAXVALUE 100000 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;



